@baseUrl = https://localhost:7179

### Check 1

POST {{baseUrl}}/api/admin/index/create
Content-Type: application/json

{
  "indexName": "labels-guide"
}

### Add Blob Document

POST {{baseUrl}}/api/admin/index/add
Content-Type: application/json

{
  "indexName": "labels-epa",
  "key" : "LABEL-KEY",
  "sourceName" : "Doc1.pdf",
  "blobName" : "Doc2.pdf"
}


### Add Blob MD Document

POST {{baseUrl}}/api/admin/index/add
Content-Type: application/json

{
  "indexName": "labels-guide",
  "key" : "Front",
  "sourceName" : "Front.md",
  "blobName" : "Front.md"
}
