@baseUrl = https://localhost:7179

/// Check 1

POST {{baseUrl}}/api/task/check1
Content-Type: application/json

{
  "taskId": "18f4fb98-dbe3-4464-95af-15ce90fabe7c",
  "files": [
    {
      "Name": "Report",
      "BlobName": "XXX_Report.pdf"
    }
  ]
}
